title: Octocat's homepage
author:
  name: Melvin Salas
  email: hello@melvinsalas.com

description: >
  Bookmark this to keep an eye on my project updates!

# theme: minima
remote_theme: "jekyll/minima"

minima:
  skin: classic
  nav_pages:
    - now.md